#!/usr/bin/env python3

import argparse
import rfpi
from rfcodes import rfswitch


if __name__ == '__main__':
    parser = argparse.ArgumentParser(prog='rftx')
    parser.add_argument('switch', nargs=1, type=int, choices=range(len(rfswitch)), help='switch number')
    parser.add_argument('onoff' , nargs=1, type=str, choices=['on', 'off'], help='on or off')
    args = parser.parse_args() 

    rf = rfpi.RF()
    rf.init()
    
    if args.onoff[0] == 'on':
        code = rfswitch[args.switch[0]].on
    else:
        code = rfswitch[args.switch[0]].off

    rf.send(code)

